BEGIN;

CREATE TABLE store (
  id SERIAL PRIMARY KEY,
  name VARCHAR(128) NOT NULL UNIQUE,
  address VARCHAR(512) NOT NULL
);

CREATE TABLE status (
  id SERIAL PRIMARY KEY,
  code VARCHAR(128) NOT NULL UNIQUE,
  name VARCHAR(128) NOT NULL UNIQUE
);

CREATE TABLE reservation (
  id SERIAL PRIMARY KEY,
  name VARCHAR(128) NOT NULL,
  store_id INTEGER NOT NULL
      REFERENCES store(id),
  status_id INTEGER NOT NULL
      REFERENCES status(id),
  date TIMESTAMP NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

COMMIT;
